import os
from sys import platform

if platform == "linux" or platform == "linux2":
    WEBDRIVER_PATH = os.path.join(os.path.dirname(os.path.realpath(__file__)), "Files\\chromedriver")
elif platform == "win32":
    WEBDRIVER_PATH = os.path.join(os.path.dirname(os.path.realpath(__file__)), "Files\\chromedriver_win.exe")

ARBITRAGE_PATH = os.path.join(os.path.dirname(os.path.realpath(__file__)), "ScrapedFiles")
RESULTS_PATH = os.path.join(os.path.dirname(os.path.realpath(__file__)), "Results")
SUMMARY_RESULTS_PATH = os.path.join(os.path.dirname(os.path.realpath(__file__)), "SummaryResults")

SLEEP_TIME = 3

BOOKMAKERS_LIST = {"EIGHT88": 0,
                   "PADDYPOWER": 1,
                   # "PINNACLE": 2,
                   "WILLIAMHILL": 3,
                   "SPORTINGBET": 4,
                   "MARATHONBET": 5
                   }

CATEGORY_LIST = ["Football_PL", "Football_C", "Football_L1", "Football_L2", "Football_CL", "Football_LaLig",
                 "Football_GeBun"]

CATEGORY_LIST = ["Football_CL", "Football_LaLig",
                 "Football_GeBun"]

EIGHT88_DICT = {"Bookmaker": "888",
                "Football_L2": "https://www.888sport.com/bet/#/filter/football/england/league_two",
                "Football_L1": "https://www.888sport.com/bet/#/filter/football/england/league_one",
                "Football_C": "https://www.888sport.com/bet/#/filter/football/england/the_championship",
                "Football_PL": "https://www.888sport.com/bet/#/filter/football/england/premier_league",
                "Football_CL": "https://www.888sport.com/bet/#/filter/football/champions_league",
                "Football_LaLig": "https://www.888sport.com/bet/#/filter/football/spain/laliga",
                "Football_GeBun": "https://www.888sport.com/bet/#/filter/football/germany/bundesliga"
                }

PADDY_DICT = {"Bookmaker": "PaddyPower",
              "Football_L2": "http://www.paddypower.com/football/football-matches/english-league-2",
              "Football_L1": "http://www.paddypower.com/football/football-matches/english-league-1",
              "Football_PL": "http://www.paddypower.com/football/football-matches/premier-league",
              "Football_CL": "http://www.paddypower.com/football/football-matches/champions-league",
              "Football_LaLig": "http://www.paddypower.com/football/football-matches/spanish-la-liga-matches",
              "Football_GeBun": "http://www.paddypower.com/football/football-matches/Germany-Bundesliga-1"
              }

PINNACLE_DICT = {"Bookmaker": "Pinnacle",
                 "Football_PL": "https://www.pinnacle.com/en/odds/match/soccer/england/england-premier-league?sport=True",
                 "Football_C": "https://www.pinnacle.com/en/odds/match/soccer/england/england-championship",
                 "Football_L1": "https://www.pinnacle.com/en/odds/match/soccer/england/england-league-1",
                 "Football_CL": "https://www.pinnacle.com/en/odds/match/soccer/uefa/uefa-champions-league"
                 }

WILLIAMHILL_DICT = {"Bookmaker": "WilliamHill",
                    "Football_PL": "http://sports.williamhill.com/bet/en-gb/betting/t/295/English+Premier+League.html",
                    "Football_C": "http://sports.williamhill.com/bet/en-gb/betting/t/292/English+Championship.html",
                    "Football_L1": "http://sports.williamhill.com/bet/en-gb/betting/t/293/English+League+1.html",
                    "Football_L2": "http://sports.williamhill.com/bet/en-gb/betting/t/294/English+League+2.html",
                    "Football_LaLig": "http://sports.williamhill.com/bet/en-gb/betting/t/338/Spanish-La-Liga-Primera.html",
                    "Football_GeBun": "http://sports.williamhill.com/bet/en-gb/betting/t/315/German+Bundesliga.html"
                   }

SPORTINGBET_DICT = {"Bookmaker": "SportingBet",
                    "Football_PL": "http://www.sportingbet.com/sports-football/england-premier-league/1-102-386195.html",
                    "Football_C": "http://www.sportingbet.com/sports-football/england-championship/1-102-851891.html",
                    "Football_L1": "http://www.sportingbet.com/sports-football/england-league-one/1-102-851967.html",
                    "Football_L2": "http://www.sportingbet.com/sports-football/england-league-two/1-102-851968.html",
                    "Football_CL": "http://www.sportingbet.com/sports-football/champions-league-201617-matches/1-102-302288.html",
                    "Football_LaLig": "http://www.sportingbet.com/sports-football/spain-primera-division/1-102-84041.html",
                    "Football_GeBun": "http://www.sportingbet.com/sports-football/germany-bundesliga/1-102-84042.html"
                   }

MARATHONBET_DICT = {"Bookmaker": "MarathonBet",
                    "Football_PL": "https://www.marathonbet.co.uk/en/popular/Football/England/Premier+League/?menu=21520",
                    "Football_C": "https://www.marathonbet.co.uk/en/popular/Football/England/Championship/?menu=22807",
                    "Football_L1": "https://www.marathonbet.co.uk/en/popular/Football/England/League+1/?menu=22808",
                    "Football_L2": "https://www.marathonbet.co.uk/en/popular/Football/England/League+2/?menu=22809",
                    "Football_CL": "https://www.marathonbet.co.uk/en/popular/Football/Clubs.+International/UEFA+Champions+League/?menu=21255",
                    "Football_LaLig": "https://www.marathonbet.co.uk/en/popular/Football/Spain/Primera+Division/?menu=8736",
                    "Football_GeBun": "https://www.marathonbet.co.uk/en/popular/Football/Germany/Bundesliga/?menu=22436"
                    }

FOOTBALL_DICT = {"ARSENAL": 1,
                 "BOURNEMOUTH": 2,
                 "BOURNEMOUTH AFC": 2,
                 "BURNLEY": 3,
                 "CHELSEA": 4,
                 "CRYSTAL PALACE": 5,
                 "EVERTON": 6,
                 "HULL CITY": 7,
                 "HULL": 7,
                 "LEICESTER CITY": 8,
                 "LEICESTER": 8,
                 "LIVERPOOL": 9,
                 "MANCHESTER CITY": 10,
                 "MAN CITY": 10,
                 "MANCHESTER UNITED": 11,
                 "MAN UTD": 11,
                 "MIDDLESBROUGH": 12,
                 "SOUTHAMPTON": 13,
                 "STOKE CITY": 14,
                 "STOKE": 14,
                 "SUNDERLAND": 15,
                 "SWANSEA CITY": 16,
                 "SWANSEA": 16,
                 "TOTTENHAM HOTSPUR": 17,
                 "TOTTENHAM": 17,
                 "WATFORD": 18,
                 "WEST BROMWICH ALBION": 19,
                 "WEST BROMWICH": 19,
                 "WEST BROM": 19,
                 "W.B.A": 19,
                 "WEST HAM UNITED": 20,
                 "WEST HAM": 20,
                 "ASTON VILLA": 101,
                 "BARNSLEY": 102,
                 "BIRMINGHAM": 103,
                 "BIRMINGHAM CITY": 103,
                 "BLACKBURN": 104,
                 "BLACKBURN ROVERS": 104,
                 "BRENTFORD": 105,
                 "BRIGHTON": 106,
                 "BRIGHTON & HOVE ALBION": 106,
                 "BRISTOL CITY": 107,
                 "BURTON ALBION": 108,
                 "BURTON": 108,
                 "CARDIFF CITY": 109,
                 "CARDIFF": 109,
                 "DERBY COUNTY": 110,
                 "DERBY": 110,
                 "FULHAM": 111,
                 "HUDDERSFIELD": 112,
                 "HUDDERSFIELD TOWN": 112,
                 "IPSWICH TOWN": 113,
                 "IPSWICH": 113,
                 "LEEDS UNITED": 114,
                 "LEEDS": 114,
                 "NEWCASTLE": 115,
                 "NEWCASTLE UNITED": 115,
                 "NORWICH CITY": 116,
                 "NORWICH": 116,
                 "NOTTM FOREST": 117,
                 "NOTTINGHAM FOREST": 117,
                 "PRESTON": 118,
                 "PRESTON NORTH END": 118,
                 "QPR": 119,
                 "QUEENS PARK RANGERS": 119,
                 "READING": 120,
                 "ROTHERHAM": 121,
                 "ROTHERHAM UNITED": 121,
                 "SHEFF WED": 122,
                 "SHEFFIELD WEDNESDAY": 122,
                 "WIGAN ATHLETIC": 123,
                 "WIGAN": 123,
                 "WOLVES": 124,
                 "WOLVERHAMPTON WANDERERS": 124,
                 "AFC WIMBLEDON": 201,
                 "WIMBLEDON": 201,
                 "BOLTON": 202,
                 "BOLTON WANDERERS": 202,
                 "BRADFORD CITY": 203,
                 "BRADFORD": 203,
                 "BRISTOL ROVERS": 204,
                 "BURY": 205,
                 "CHARLTON": 206,
                 "CHARLTON ATHLETIC": 206,
                 "CHESTERFIELD": 207,
                 "COVENTRY": 208,
                 "COVENTRY CITY": 208,
                 "FLEETWOOD": 209,
                 "FLEETWOOD TOWN": 209,
                 "GILLINGHAM": 210,
                 "MILLWALL": 211,
                 "MK DONS": 212,
                 "MILTON KEYNES DONS": 212,
                 "NORTHAMPTON": 213,
                 "NORTHAMPTON TOWN": 213,
                 "OLDHAM": 214,
                 "OLDHAM ATHLETIC": 214,
                 "OXFORD": 215,
                 "OXFORD UNITED": 215,
                 "PETERBOROUGH": 216,
                 "PETERBOROUGH UNITED": 216,
                 "PORT VALE": 217,
                 "ROCHDALE": 218,
                 "SCUNTHORPE": 219,
                 "SCUNTHORPE UNITED": 219,
                 "SHEFF UTD": 220,
                 "SHEFFIELD UNITED": 220,
                 "SHREWSBURY": 221,
                 "SHREWSBURY TOWN": 221,
                 "SOUTHEND UTD": 222,
                 "SOUTHEND": 222,
                 "SOUTHEND UNITED": 222,
                 "SWINDON TOWN": 223,
                 "SWINDON": 223,
                 "WALSALL": 224,
                 "WALLSALL": 224,
                 "ACCRINGTON STANLEY": 301,
                 "ACCRINGTON": 301,
                 "BARNET": 302,
                 "BLACKPOOL": 303,
                 "CAMBRIDGE UNITED": 304,
                 "CAMBRIDGE": 304,
                 "CAMBRIDGE U": 304,
                 "CARLISLE UNITED": 305,
                 "CHELTENHAM TOWN": 306,
                 "COLCHESTER UNITED": 307,
                 "CRAWLEY TOWN": 308,
                 "CREWE ALEXANDRA": 309,
                 "DONCASTER ROVERS": 310,
                 "EXETER CITY": 311,
                 "GRIMSBY TOWN": 312,
                 "HARTLEPOOL UNITED": 313,
                 "LEYTON ORIENT": 314,
                 "LUTON TOWN": 315,
                 "MANSFIELD TOWN": 316,
                 "MORECAMBE": 317,
                 "NEWPORT COUNTY": 318,
                 "NEWPORT": 318,
                 "NOTTS COUNTY": 319,
                 "NOTTS CO.": 319,
                 "PLYMOUTH ARGYLE": 320,
                 "PORTSMOUTH": 321,
                 "STEVENAGE": 322,
                 "WYCOMBE WANDERERS": 323,
                 "YEOVIL TOWN": 324,
                 "EXETER": 311,
                 "CHELTENHAM": 306,
                 "STEVENAGE FC": 322,
                 "CARLISLE": 305,
                 "DONCASTER": 310,
                 "COLCHESTER": 307,
                 "CRAWLEY": 308,
                 "CREWE": 309,
                 "YEOVIL": 324,
                 "GRIMSBY": 312,
                 "HARTLEPOOL": 313,
                 "LUTON": 315,
                 "MANSFIELD": 316,
                 "PLYMOUTH": 320,
                 "WYCOMBE": 323,
                 "BESIKTAS": 401,
                 "BEIKTA A..": 401,
                 "NAPOLI": 402,
                 "SSC NAPOLI": 402,
                 "ATLTICO MADRID": 403,
                 "ATLETICO MADRID": 403,
                 "FC ROSTOV": 404,
                 "ROSTOV FK": 404,
                 "ROSTOV": 404,
                 "BASEL": 405,
                 "FC BASEL": 405,
                 "FX ROSTOV": 404,
                 "FK ROSTOV": 404,
                 "PARIS SG": 407,
                 "PARIS SAINT GERMAIN": 407,
                 "PARIS SAINT-GERMAIN": 407,
                 "PSG": 407,
                 "BENFICA": 408,
                 "DYNAMO KIEV": 409,
                 "DYNAMO KYIV": 409,
                 "BORUSSIA MONCHENGLADBACH": 410,
                 "BORUSSIA MNCHENGLADBACH": 410,
                 "BORUSSIA MOENCHENGLADBACH": 410,
                 "CELTIC": 411,
                 "CELTIC FC": 411,
                 "LUDOGORETS RAZGRAD": 412,
                 "LUDOGORETS RAZGRAD (N)": 412,
                 "BARCELONA": 413,
                 "FC BARCELONA": 413,
                 "PSV": 414,
                 "PSV EINDHOVEN": 414,
                 "BAYERN MUNICH": 415,
                 "BAYERN MNCHEN": 415,
                 "BAYERN MUNCHEN": 415,
                 "BORUSSIA DORTMUND": 416,
                 "DORTMUND": 416,
                 "SPORTING LISBON": 417,
                 "SPORTING LISBOA": 417,
                 "SPORTING CP": 417,
                 "FC COPENHAGEN": 418,
                 "JUVENTUS": 419,
                 "LYON": 420,
                 "FC PORTO": 421,
                 "PORTO": 421,
                 "LEGIA WARSAW": 422,
                 "LEGIA WARSZAWA": 422,
                 "CLUB BRUGGE": 423,
                 "CLUB BRUGES": 423,
                 "BRUGGE": 423,
                 "REAL MADRID": 424,
                 "MONACO": 425,
                 "AS MONACO": 425,
                 "CSKA MOSCOW": 426,
                 "DINAMO ZAGREB": 428,
                 "BAYER LEERKUSEN": 429,
                 "BAYER LEVERKUSEN": 429,
                 "BAYER 04 LEVERKUSEN": 429,
                 "LEVERKUSEN": 429,
                 "REAL MADRD": 430,
                 "SEVILLA": 431,
                 "VILLARREAL": 433,
                 "ATHLETIC BILBAO": 435,
                 "ATHLETIC CLUB BILBAO": 435,
                 "REAL SOCIEDAD": 436,
                 "CELTA VIGO": 437,
                 "LAS PALMAS": 438,
                 "DEPORTIVA LAS PALMAS": 438,
                 "MALAGA": 439,
                 "MLAGA": 439,
                 "EIBAR": 440,
                 "REAL BETIS": 441,
                 "BETIS": 441,
                 "ALAVES": 442,
                 "ALAVS": 442,
                 "VALENCIA": 443,
                 "ESPANYOL": 444,
                 "DEPORTIVO LA CORUNA": 445,
                 "DEPORTIVO LA CORUA": 445,
                 "SPORTING GIJON": 446,
                 "SPORTING DE GIJN": 446,
                 "GRANADA": 447,
                 "GRANADA CF": 447,
                 "LEGANES": 448,
                 "LEGANS": 448,
                 "OSASUNA": 449,
                 "RB LEIPZIG": 451,
                 "LEIPZIG": 451,
                 "RASENBALLSPORT LEIPZIG": 451,
                 "HERTHA BERLIN": 452,
                 "HOFFENHEIM": 453,
                 "COLOGNE": 454,
                 "FC COLOGNE": 454,
                 "1. FC KLN": 454,
                 "FC KOLN": 454,
                 "EINTRACHT FRANKFURT": 456,
                 "SC FREIBURG": 457,
                 "FREIBURG": 457,
                 "MAINZ": 458,
                 "MAINZ 05": 458,
                 "FSV MAINZ 05": 458,
                 "M'GLADBACH": 459,
                 "FC AUGSBURG": 461,
                 "AUGSBURG": 461,
                 "SCHALKE": 462,
                 "SCHALKE 04": 462,
                 "WERDER BREMEN": 463,
                 "WOLFSBURG": 464,
                 "VFL WOLFSBURG": 464,
                 "FC INGOLSTADT 04": 465,
                 "FC INGOLSTADT": 465,
                 "INGOLSTADT": 465,
                 "HAMBURG": 466,
                 "HAMBURGER SV": 466,
                 "SV DARMSTADT 98": 467,
                 "DARMSTADT 98": 467,
                 "DARMSTADT": 467
                 }
CATEGORY_DICT = {"FOOTBALL": 1}

PARTICIPANT_DICT = dict()
PARTICIPANT_DICT["FOOTBALL"] = FOOTBALL_DICT

SUBCATEGORY_DICT = dict()
SUBCATEGORY_DICT["FOOTBALL"] = {"PREMIER LEAGUE": 1,
                                "ENGLAND-PREMIERLEAGUE": 1,
                                "ENGLISH PREMIER LEAGUE": 1,
                                "ENGLAND - PREMIER LEAGUE": 1,
                                "ENGLAND. PREMIER LEAGUE": 1,
                                "THE CHAMPIONSHIP": 2,
                                "ENGLISH CHAMPIONSHIP": 2,
                                "ENGLAND - CHAMPIONSHIP": 2,
                                "ENGLAND. CHAMPIONSHIP": 2,
                                "ENGLAND. LEAGUE 1": 3,
                                "ENGLISH LEAGUE 1": 3,
                                "ENGLAND - LEAGUE ONE": 3,
                                "LEAGUE ONE": 3,
                                "ENGLAND. LEAGUE 2": 4,
                                "ENGLISH LEAGUE 2": 4,
                                "LEAGUE TWO": 4,
                                "ENGLAND - LEAGUE TWO": 4,
                                "CLUBS. INTERNATIONAL. UEFA CHAMPIONS LEAGUE. GROUP STAGE": 11,
                                "FA CUP": 12}

BOOKMAKERS = [EIGHT88_DICT,
              PADDY_DICT,
              PINNACLE_DICT,
              WILLIAMHILL_DICT,
              SPORTINGBET_DICT,
              MARATHONBET_DICT
              ]
